[package]
name = "chess_bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
env_logger = "0.11.5"
fchess = { path = "../fchess" }

[profile.release]
strip = true
lto = true
