[package]
name = "fchess"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2"

[profile.release]
lto = true
panic = "abort"
debug = 2
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native"]